name:               "yusuke wakuta"
description:        "portfolio of yusuke wakuta"

url:                ""
author:             "yusuke wakuta"
email:              "wakuta.yusuke@ist.osaka-u.ac.jp"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "@yusuke_wk"
email:              "wakuta.yusuke@ist.osaka-u.ac.jp"
github:             "Y-Wakuta"
linkedin:           "涌田 悠佑"
hatena:             "https://yusuke-haimenhikou.hatenablog.com"

disqus_shortname:   "thinker3197"

#background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About Me"
    href:           "#aboutme"
  - name:           "Research Interest"
    href:           "#research"
  - name:           "Personal Interest"
    href:           "#personal"
  - name:           "Career"
    href:           "#career"
  - name:           "History"
    href:           "#history"
  - name:           "Club Activity"
    href:           "#club"
  - name:           "Hobby"
    href:           "#hobby"

sass:
  style:            :compressed
